# Generated by Django 2.1.5 on 2019-02-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_path_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('alarm', models.BooleanField(default=False)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.Path')),
            ],
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
